# Generated by Django 4.0.4 on 2022-04-28 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Useer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useertype', models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('qa', 'Quality Assurance')], default='developer', max_length=30, verbose_name='User Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='Project Name')),
                ('useer', models.ManyToManyField(to='bugzilla.useer')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug')], default='bug', max_length=20)),
                ('bugcreater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creater', to='bugzilla.useer', verbose_name='Bug Creater')),
                ('bugsolver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solver', to='bugzilla.useer', verbose_name='Bug Solver')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='bugzilla.project')),
            ],
        ),
    ]
